language: go
sudo: required
dist: trusty
before_install:
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
go:
  - tip
  - 1.5
os:
  - linux
