language: go
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - sudo dpkg -i wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
go:
  - tip
  - 1.5
os:
  - linux
