language: go
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd wkhtmltox/bin/ ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo mv wkhtmltopdf /usr/bin/wkhtmltopdf ; fi
go:
  - 1.9
script: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .  
